# NOTICE: Harbor chart is not dependent on other charts. This is just a mock for UT coverage.
dependencies:
  - name: postgresql
    version: 16.0.4
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 20.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
