{{- if and (hasKey .Values "persistence") (hasKey .Values.persistence "persistentVolumeClaim") (hasKey .Values.persistence.persistentVolumeClaim "trivy") }}
# Your StatefulSet configuration when persistence is enabled for Trivy
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trivy-sts
  labels:
    {{ include "harbor.labels" . | indent 4 }}
spec:
  serviceName: "trivy"
  replicas: 1
  selector:
    matchLabels:
      app: trivy
  template:
    metadata:
      labels:
        app: trivy
    spec:
      containers:
        - name: trivy
          image: "goharbor/trivy-adapter:latest"
          volumeMounts:
            - name: trivy-pvc
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: trivy-pvc
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.persistence.persistentVolumeClaim.trivy.size }}
{{- else }}
# Your StatefulSet configuration when persistence for Trivy is disabled or undefined
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trivy-sts
  labels:
    {{ include "harbor.labels" . | indent 4 }}
spec:
  serviceName: "trivy"
  replicas: 1
  selector:
    matchLabels:
      app: trivy
  template:
    metadata:
      labels:
        app: trivy
    spec:
      containers:
        - name: trivy
          image: "goharbor/trivy-adapter:latest"
{{- end }}
